[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://gleeful-douhua-c4e8c8.netlify.app/*"
  to = "https://yoqubkhoja.tj/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
